conventions: |
  <memory_service_rules>
  | Message | Required |
  |---------|----------|
  | **1st message** | `memory_health()` → `memory_search(query="...", mode="hybrid")` |
  | **Subsequent messages (default)** | `memory_search(query="...", mode="hybrid")` FIRST for recall |
  | **Before ending major work** | `memory_store(content="...", metadata={...})` |
  </memory_service_rules>

  **Why?** MCP Memory Service provides persistent memory recall across sessions.

  **Session start protocol:**
  1) Verify service health with `memory_health()`.
  2) Recall context via `memory_search(query="<first_message>", mode="hybrid", limit=8)`.
  3) Use local repo search tools for code navigation.

  **Capture protocol:**
  - Decision: `memory_store(content="...", metadata={"tags":["decision"],"type":"decision"})`
  - Bug/Fix: `memory_store(content="...", metadata={"tags":["bug","fix"],"type":"error"})`
  - Checkpoint: `memory_store(content="...", metadata={"tags":["checkpoint"],"type":"note"})`

  **Install/update:**
  - `pip install -U mcp-memory-service`
  - `uvx --from mcp-memory-service memory server`
  - `python -m mcp_memory_service.server`

