/* ###
 * IP: AgentDecompile
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package agentdecompile.plugin;

import static org.junit.Assert.*;

import org.junit.Before;
import org.junit.Test;

import agentdecompile.plugin.ConfigManager;
import ghidra.framework.options.ToolOptions;
import ghidra.framework.plugintool.PluginTool;
import agentdecompile.AgentDecompileIntegrationTestBase;

/**
 * Test class for ConfigManager security-related configuration options.
 */
public class ConfigManagerSecurityTest extends AgentDecompileIntegrationTestBase {

    @Override
    protected boolean shouldLoadPlugin() {
        // This test doesn't need the GUI plugin, just the tool for ToolOptions
        return false;
    }

    private ConfigManager configManager;

    @Before
    public void setUp() throws Exception {
        // Clear any existing configuration to start fresh
        ToolOptions options = tool.getOptions(ConfigManager.SERVER_OPTIONS);

        // Force set an empty API key to ensure generation of a new one
        options.setString(ConfigManager.API_KEY, "");

        // Create a fresh ConfigManager for each test to avoid state pollution
        // This will register default options and generate a new API key
        configManager = new ConfigManager(tool);
    }

    @Test
    public void testDefaultHostConfiguration() {
        // Test that the default host is localhost (secure by default)
        String defaultHost = configManager.getServerHost();
        assertEquals("Default host should be localhost for security", "127.0.0.1", defaultHost);
    }

    @Test
    public void testDefaultApiKeyConfiguration() {
        // Test that API key authentication is disabled by default
        boolean apiKeyEnabled = configManager.isApiKeyEnabled();
        assertFalse("API key authentication should be disabled by default", apiKeyEnabled);

        // Test that an API key is generated by default
        String apiKey = configManager.getApiKey();
        assertNotNull("API key should not be null", apiKey);
        assertFalse("API key should not be empty", apiKey.trim().isEmpty());
        assertTrue("API key should start with 'AgentDecompile-'", apiKey.startsWith("AgentDecompile-"));
        assertTrue("API key should contain a UUID", apiKey.length() > 10);
    }

    @Test
    public void testHostConfigurationUpdate() {
        // Test updating the host configuration
        String newHost = "0.0.0.0";
        configManager.setServerHost(newHost);
        assertEquals("Host should be updated", newHost, configManager.getServerHost());
    }

    @Test
    public void testApiKeyConfigurationUpdate() {
        // Test enabling API key authentication
        configManager.setApiKeyEnabled(true);
        assertTrue("API key authentication should be enabled", configManager.isApiKeyEnabled());

        // Test setting a custom API key
        String customApiKey = "AgentDecompile-custom-test-key";
        configManager.setApiKey(customApiKey);
        assertEquals("Custom API key should be set", customApiKey, configManager.getApiKey());
    }

    @Test
    public void testApiKeyGenerationFormat() {
        // Test that generated API keys follow the expected format
        String apiKey = configManager.getApiKey();
        String[] parts = apiKey.split("-", 2);

        assertEquals("API key should start with 'AgentDecompile'", "AgentDecompile", parts[0]);
        assertEquals("API key should have UUID part", 2, parts.length);
        assertTrue("UUID part should be non-empty", parts[1].length() > 0);
        // UUID with dashes is typically 36 characters, but let's be more lenient
        assertTrue("UUID part should be reasonable length", parts[1].length() >= 10);
    }

    @Test
    public void testConfigurationPersistence() {
        // Test that configuration changes are persisted through the options system
        ToolOptions options = tool.getOptions(ConfigManager.SERVER_OPTIONS);

        // Set values through ConfigManager
        configManager.setServerHost("192.168.1.100");
        configManager.setApiKeyEnabled(true);
        configManager.setApiKey("AgentDecompile-test-persistence");

        // Verify values are stored in tool options
        assertEquals("Host should be persisted in options",
                     "192.168.1.100", options.getString(ConfigManager.SERVER_HOST, null));
        assertTrue("API key enabled should be persisted in options",
                   options.getBoolean(ConfigManager.API_KEY_ENABLED, false));
        assertEquals("API key should be persisted in options",
                     "AgentDecompile-test-persistence", options.getString(ConfigManager.API_KEY, null));
    }
}