"""Prove a reconstructed Unity project actually opens, then repair it when it doesn't.

A composed project is a pile of files until an Editor has imported it. Everything
upstream -- AssetRipper output, ILSpy source, a hand-written manifest -- can look
complete on disk and still fail to open: duplicate ``[assembly: ...]`` attributes
from decompiled ``AssemblyInfo.cs`` (CS0579), types that reference assemblies that
were never copied into ``Plugins/`` (CS0246), MonoBehaviours whose script GUIDs
point at nothing. This module is the gate that turns "files exist" into "an Editor
imported it and reported N errors".

The load-bearing design decision is **no MCP bridge and no interactive Editor**.
An open Editor window only rescans the asset folder when its background scanner
gets around to it, and when the window lacks OS focus that can take minutes or
never happen at all -- a previous run of this pipeline stalled for a long time
waiting on exactly that. A cold ``-batchmode -quit -nographics`` open performs a
full import unconditionally, writes a deterministic log, and exits. So every
verification here goes through :func:`agentdecompile_recovery.tools.run_unity_batchmode`.

Three layers, deliberately separated so the fragile part is testable without Unity:

* the injected C# probe (:data:`VALIDATOR_SOURCE`) -- runs *inside* the Editor.
* pure parsers and the recipe classifier -- string in, dicts out, never raise.
* orchestration (:func:`validate_unity_project`, :func:`repair_unity_project`) --
  the only functions that spawn a process or touch the project tree.

Note the asymmetry that makes the log parsers indispensable: when compilation
fails, Unity refuses to invoke ``-executeMethod`` at all, so the JSON report is
never written and the *log* is the only evidence. A missing report is therefore a
finding, not an error.
"""

from __future__ import annotations

import json
import os
import re
import subprocess
import time
from pathlib import Path
from typing import Any, Callable

from .tools import ToolchainError, run_unity_batchmode

# -- validator identity -------------------------------------------------------
# The class lives in the global namespace, so the -executeMethod path is simply
# `Class.Method`. Keep these three constants consistent with VALIDATOR_SOURCE.
VALIDATOR_METHOD = "ADRecoveryValidate.Run"
VALIDATOR_RELATIVE_PATH = Path("Assets/Editor/ADRecoveryValidate.cs")
VALIDATOR_OUT_ENV = "ADRECOVERY_VALIDATE_OUT"
VALIDATOR_REPORT_RELATIVE_PATH = Path("Temp/adrecovery-validate.json")
VALIDATOR_LOG_MARKER = "[ADRecoveryValidate]"


# Raw string: the C# below contains backslash escapes that must survive verbatim.
VALIDATOR_SOURCE: str = r"""// <auto-generated>
// Written by agentdecompile_recovery.unity_editor.install_validator().
// Purpose: prove, from inside a batchmode Editor, that this project imports,
// compiles, and can open its scenes. Safe to delete; it is regenerated on every
// validation run and never referenced by game code.
// Target: Unity 2021.3+. Anything version-risky goes through reflection.
using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Text;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;

public static class ADRecoveryValidate
{
    const string OutEnv = "ADRECOVERY_VALIDATE_OUT";
    const string Marker = "[ADRecoveryValidate]";

    // Cap the AssetDatabase fallback: a project with hundreds of scenes would
    // turn verification into an overnight job for no extra proof.
    const int MaxFallbackScenes = 64;

    public static void Run()
    {
        string outPath = ResolveOutPath();
        string json;
        try
        {
            json = BuildReport();
        }
        catch (Exception e)
        {
            json = "{\"schema\":\"adrecovery.validate.v1\",\"status\":\"error\",\"error\":\""
                 + Esc(e.GetType().Name + ": " + e.Message) + "\"}";
        }

        try
        {
            string dir = Path.GetDirectoryName(outPath);
            if (!string.IsNullOrEmpty(dir) && !Directory.Exists(dir)) Directory.CreateDirectory(dir);
            File.WriteAllText(outPath, json);
            Debug.Log(Marker + " wrote report: " + outPath);
        }
        catch (Exception e)
        {
            // The report is the whole point of this method; failing to write it
            // is the one internal failure worth a non-zero exit.
            Debug.LogError(Marker + " failed to write report to " + outPath + ": " + e.Message);
            EditorApplication.Exit(2);
            return;
        }
        EditorApplication.Exit(0);
    }

    static string ResolveOutPath()
    {
        string configured = null;
        try { configured = Environment.GetEnvironmentVariable(OutEnv); } catch { }
        if (!string.IsNullOrEmpty(configured)) return configured;
        // Application.dataPath is "<project>/Assets"; batchmode cwd is not reliable.
        string projectRoot;
        try { projectRoot = Path.GetDirectoryName(Application.dataPath); }
        catch { projectRoot = Directory.GetCurrentDirectory(); }
        return Path.Combine(Path.Combine(projectRoot, "Temp"), "adrecovery-validate.json");
    }

    static string BuildReport()
    {
        var scenePaths = new List<string>();
        var sceneEnabled = new List<bool>();
        string sceneSource = "buildSettings";
        string fatal = "";

        try
        {
            foreach (var entry in EditorBuildSettings.scenes)
            {
                if (entry == null || string.IsNullOrEmpty(entry.path)) continue;
                scenePaths.Add(entry.path);
                sceneEnabled.Add(entry.enabled);
            }
        }
        catch (Exception e) { fatal = e.GetType().Name + ": " + e.Message; }

        if (scenePaths.Count == 0)
        {
            // An empty build-settings list is common in reconstructed projects.
            // Falling back to on-disk scenes keeps the run from proving nothing;
            // sceneSource records which list was actually used.
            sceneSource = "assetDatabase";
            try
            {
                foreach (var guid in AssetDatabase.FindAssets("t:Scene"))
                {
                    string path = AssetDatabase.GUIDToAssetPath(guid);
                    if (string.IsNullOrEmpty(path)) continue;
                    if (!path.StartsWith("Assets/")) continue;
                    scenePaths.Add(path);
                    sceneEnabled.Add(false);
                    if (scenePaths.Count >= MaxFallbackScenes) break;
                }
            }
            catch (Exception e) { if (fatal.Length == 0) fatal = e.GetType().Name + ": " + e.Message; }
        }

        int opened = 0;
        int missingTotal = 0;
        var scenes = new StringBuilder();

        for (int i = 0; i < scenePaths.Count; i++)
        {
            string path = scenePaths[i];
            bool sceneOpened = false;
            int rootCount = 0;
            int missing = 0;
            string error = "";
            try
            {
                Scene scene = EditorSceneManager.OpenScene(path, OpenSceneMode.Single);
                sceneOpened = scene.IsValid();
                if (sceneOpened)
                {
                    opened++;
                    GameObject[] roots = scene.GetRootGameObjects();
                    rootCount = roots.Length;
                    for (int r = 0; r < roots.Length; r++) missing += CountMissingScripts(roots[r]);
                    missingTotal += missing;
                }
            }
            catch (Exception e)
            {
                error = e.GetType().Name + ": " + e.Message;
            }

            if (scenes.Length > 0) scenes.Append(",");
            scenes.Append("{\"path\":\"").Append(Esc(path)).Append("\"")
                  .Append(",\"enabled\":").Append(sceneEnabled[i] ? "true" : "false")
                  .Append(",\"opened\":").Append(sceneOpened ? "true" : "false")
                  .Append(",\"rootCount\":").Append(rootCount)
                  .Append(",\"missingScripts\":").Append(missing)
                  .Append(",\"error\":\"").Append(Esc(error)).Append("\"}");
        }

        var sb = new StringBuilder();
        sb.Append("{\"schema\":\"adrecovery.validate.v1\"")
          .Append(",\"status\":\"").Append(fatal.Length == 0 ? "ok" : "partial").Append("\"")
          .Append(",\"error\":\"").Append(Esc(fatal)).Append("\"")
          .Append(",\"unityVersion\":\"").Append(Esc(SafeUnityVersion())).Append("\"")
          .Append(",\"projectPath\":\"").Append(Esc(SafeProjectPath())).Append("\"")
          .Append(",\"sceneSource\":\"").Append(sceneSource).Append("\"")
          .Append(",\"sceneTotal\":").Append(scenePaths.Count)
          .Append(",\"scenesOpened\":").Append(opened)
          .Append(",\"missingScriptTotal\":").Append(missingTotal)
          .Append(",\"compile\":").Append(CompileStateJson())
          .Append(",\"scenes\":[").Append(scenes.ToString()).Append("]}");
        return sb.ToString();
    }

    static int CountMissingScripts(GameObject go)
    {
        if (go == null) return 0;
        int count = 0;
        try { count += UnityEditor.GameObjectUtility.GetMonoBehavioursWithMissingScriptCount(go); }
        catch { }
        Transform t = go.transform;
        for (int i = 0; i < t.childCount; i++) count += CountMissingScripts(t.GetChild(i).gameObject);
        return count;
    }

    static string CompileStateJson()
    {
        // scriptCompilationFailed has moved between public and internal across
        // versions, so read it reflectively rather than failing to compile.
        string failed = "null";
        try
        {
            PropertyInfo prop = typeof(EditorUtility).GetProperty(
                "scriptCompilationFailed",
                BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Static);
            if (prop != null)
            {
                object value = prop.GetValue(null, null);
                if (value is bool) failed = ((bool)value) ? "true" : "false";
            }
        }
        catch { failed = "null"; }

        bool isCompiling = false;
        try { isCompiling = EditorApplication.isCompiling; } catch { }

        int playerAssemblies = -1;
        int editorAssemblies = -1;
        try
        {
            playerAssemblies = UnityEditor.Compilation.CompilationPipeline
                .GetAssemblies(UnityEditor.Compilation.AssembliesType.Player).Length;
            editorAssemblies = UnityEditor.Compilation.CompilationPipeline
                .GetAssemblies(UnityEditor.Compilation.AssembliesType.Editor).Length;
        }
        catch { }

        return "{\"compilationFailed\":" + failed
             + ",\"isCompiling\":" + (isCompiling ? "true" : "false")
             + ",\"playerAssemblyCount\":" + playerAssemblies
             + ",\"editorAssemblyCount\":" + editorAssemblies + "}";
    }

    static string SafeUnityVersion()
    {
        try { return Application.unityVersion; } catch { return ""; }
    }

    static string SafeProjectPath()
    {
        try { return Path.GetDirectoryName(Application.dataPath); } catch { return ""; }
    }

    // Hand-rolled JSON escaping: JsonUtility cannot express a nested array of
    // objects without declaring serializable types, and Newtonsoft is not
    // guaranteed present in a reconstructed project.
    static string Esc(string value)
    {
        if (string.IsNullOrEmpty(value)) return "";
        var sb = new StringBuilder(value.Length + 16);
        foreach (char c in value)
        {
            switch (c)
            {
                case '"': sb.Append("\\\""); break;
                case '\\': sb.Append("\\\\"); break;
                case '\n': sb.Append("\\n"); break;
                case '\r': sb.Append("\\r"); break;
                case '\t': sb.Append("\\t"); break;
                default:
                    if (c < ' ') sb.Append("\\u").Append(((int)c).ToString("x4"));
                    else sb.Append(c);
                    break;
            }
        }
        return sb.ToString();
    }
}
"""


def install_validator(project_path: Path) -> Path:
    """Write the C# probe into ``<project>/Assets/Editor/`` and return its path.

    Rewritten on every call so a stale probe from an older version of this module
    can never silently determine the shape of a report.
    """

    target = Path(project_path) / VALIDATOR_RELATIVE_PATH
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(VALIDATOR_SOURCE, encoding="utf-8")
    return target


def validator_report_path(project_path: Path) -> Path:
    """Where the probe writes its JSON report when ``ADRECOVERY_VALIDATE_OUT`` is set."""

    return Path(project_path) / VALIDATOR_REPORT_RELATIVE_PATH


# ---------------------------------------------------------------------------
# Part 2 -- log parsing. Pure functions: string in, list of dicts out, never raise.
# ---------------------------------------------------------------------------

# A C# source path as it appears in a Unity compile error. Colons are excluded so
# the match cannot swallow a "Some prefix: " lead-in, with an explicit opt-in for
# a Windows drive letter.
_CS_FILE = r"(?:[A-Za-z]:[\\/])?[^\s:*?\"<>|\r\n][^:*?\"<>|\r\n]*?\.[cC][sS]"

_COMPILE_ERROR_RE = re.compile(
    rf"(?P<file>{_CS_FILE})\s*\(\s*(?P<line>\d+)\s*(?:,\s*(?P<column>\d+)\s*)?\)\s*:\s*"
    r"(?:error|ERROR|Error)\s+(?P<code>[A-Za-z]{1,4}\d{3,5})\s*:\s*(?P<message>[^\r\n]*)"
)

# Errors Unity reports without a file location (missing assembly references,
# csc driver errors). Still actionable, so they are captured with file=None.
_BARE_ERROR_RE = re.compile(
    r"(?<![\w.])(?:error|ERROR)\s+(?P<code>CS\d{3,5})\s*:\s*(?P<message>[^\r\n]*)"
)

# msbuild-style trailing project annotation, e.g. " [/path/Assembly-CSharp.csproj]".
_TRAILING_PROJECT_RE = re.compile(r"\s*\[[^\]\r\n]*\.(?:csproj|sln)\]\s*$")


def _clean_message(raw: str) -> str:
    return _TRAILING_PROJECT_RE.sub("", (raw or "").strip()).strip()


def _as_text(value: Any) -> str:
    if isinstance(value, str):
        return value
    if isinstance(value, (bytes, bytearray)):
        return value.decode("utf-8", "replace")
    if value is None:
        return ""
    try:
        return str(value)
    except Exception:  # noqa: BLE001 - a parser must never raise on weird input
        return ""


def parse_compile_errors(log_text: str) -> list[dict[str, Any]]:
    """Extract deduplicated C# compile errors from a Unity Editor log.

    Handles the canonical ``File.cs(line,col): error CSxxxx: message`` form plus
    the column-less and file-less variants Unity emits from different compiler
    drivers. Order of first appearance is preserved -- the first error is usually
    the causal one.
    """

    text = _as_text(log_text)
    if not text:
        return []

    out: dict[tuple[Any, ...], dict[str, Any]] = {}
    spans: list[tuple[int, int]] = []

    try:
        matches = list(_COMPILE_ERROR_RE.finditer(text))
    except Exception:  # noqa: BLE001
        matches = []
    for match in matches:
        spans.append(match.span())
        file_path = (match.group("file") or "").strip()
        column = match.group("column")
        entry = {
            "file": file_path or None,
            "line": int(match.group("line")),
            "column": int(column) if column is not None else None,
            "code": match.group("code").upper(),
            "message": _clean_message(match.group("message")),
        }
        out.setdefault(
            (entry["file"], entry["line"], entry["column"], entry["code"], entry["message"]),
            entry,
        )

    try:
        bare_matches = list(_BARE_ERROR_RE.finditer(text))
    except Exception:  # noqa: BLE001
        bare_matches = []
    for match in bare_matches:
        start = match.start()
        if any(begin <= start < end for begin, end in spans):
            continue
        entry = {
            "file": None,
            "line": None,
            "column": None,
            "code": match.group("code").upper(),
            "message": _clean_message(match.group("message")),
        }
        out.setdefault((None, None, None, entry["code"], entry["message"]), entry)

    return list(out.values())


# Unity's phrasing for a broken script reference varies by version and by whether
# the owning GameObject could be named at the point of the log write.
_MISSING_REFERENCE_PATTERNS: tuple[tuple[re.Pattern[str], str], ...] = (
    (
        re.compile(
            r"The referenced script(?:\s*\((?P<script>[^)\r\n]*)\))?\s+on this Behaviour"
            r"(?:\s*\((?:Game ?Object|GameObject)\s*'(?P<go>[^'\r\n]*)'\))?\s+is missing!?",
            re.IGNORECASE,
        ),
        "missing-script",
    ),
    (
        re.compile(
            r"(?:The referenced script|Script) (?:attached to|on) '(?P<go>[^'\r\n]*)'"
            r"[^\r\n]*?is missing[^\r\n]*",
            re.IGNORECASE,
        ),
        "missing-script",
    ),
    (
        re.compile(
            r"(?:Missing|Unknown)\s*\(\s*Mono\s*Script\s*\)(?:[^\r\n]*)",
            re.IGNORECASE,
        ),
        "missing-script",
    ),
    (
        re.compile(r"Missing GUID\s+(?P<guid>[0-9a-fA-F]{32})[^\r\n]*", re.IGNORECASE),
        "missing-guid",
    ),
    (
        re.compile(
            r"GUID\s+(?P<guid>[0-9a-fA-F]{32})[^\r\n]*?"
            r"(?:is missing|not found|cannot be found|could not be found)[^\r\n]*",
            re.IGNORECASE,
        ),
        "missing-guid",
    ),
    (
        re.compile(r"Could not extract GUID[^\r\n]*", re.IGNORECASE),
        "missing-guid",
    ),
    (
        re.compile(
            r"A script behaviour[^\r\n]*?(?:has a different serialization layout|"
            r"is missing|could not be loaded)[^\r\n]*",
            re.IGNORECASE,
        ),
        "script-layout-mismatch",
    ),
)

_ANY_GUID_RE = re.compile(r"\b([0-9a-fA-F]{32})\b")


def _scan_claimed_lines(
    text: str,
    patterns: tuple[tuple[re.Pattern[str], str], ...],
) -> list[tuple[str, re.Match[str], str]]:
    """Match ``patterns`` against ``text``, at most one hit per log line.

    Unity writes one diagnostic per line, and several of these patterns
    deliberately overlap (a generic tag plus a specific phrasing). Without this,
    a single failure would be reported two or three times and inflate every count
    the repair loop's convergence guard depends on. Patterns are tried in order,
    so the most specific one must come first.
    """

    claimed: set[int] = set()
    hits: list[tuple[int, str, re.Match[str], str]] = []
    for pattern, kind in patterns:
        try:
            matches = list(pattern.finditer(text))
        except Exception:  # noqa: BLE001 - a parser must never raise
            continue
        for match in matches:
            line_index = text.count("\n", 0, match.start())
            if line_index in claimed:
                continue
            claimed.add(line_index)
            line_start = text.rfind("\n", 0, match.start()) + 1
            line_end = text.find("\n", match.start())
            line_text = text[line_start : line_end if line_end != -1 else len(text)].strip()
            hits.append((line_index, kind, match, line_text))
    hits.sort(key=lambda hit: hit[0])
    return [(kind, match, line_text) for _, kind, match, line_text in hits]


def parse_missing_references(log_text: str) -> list[dict[str, Any]]:
    """Extract missing script / missing GUID reports, with repeat counts.

    Unity logs one line per broken Behaviour instance, so a single dead script can
    produce thousands of identical lines; ``occurrences`` keeps that signal without
    the volume.
    """

    text = _as_text(log_text)
    if not text:
        return []

    out: dict[tuple[Any, ...], dict[str, Any]] = {}
    for kind, match, line_text in _scan_claimed_lines(text, _MISSING_REFERENCE_PATTERNS):
        groups = match.groupdict()
        guid = groups.get("guid")
        if not guid:
            guid_match = _ANY_GUID_RE.search(line_text)
            guid = guid_match.group(1) if guid_match else None
        entry = {
            "kind": kind,
            "gameObject": (groups.get("go") or None),
            "script": (groups.get("script") or None),
            "guid": guid.lower() if guid else None,
            "message": (match.group(0) or "").strip(),
            "raw": line_text,
            "occurrences": 1,
        }
        key = (entry["kind"], entry["gameObject"], entry["script"], entry["guid"], entry["raw"])
        existing = out.get(key)
        if existing is None:
            out[key] = entry
        else:
            existing["occurrences"] += 1
    return list(out.values())


_PACKAGE_ID_RE = re.compile(r"\b((?:com|org|net)\.[A-Za-z0-9_.\-]+(?:@[^\s,;\]\"')]+)?)")

_PACKAGE_ERROR_PATTERNS: tuple[tuple[re.Pattern[str], str], ...] = (
    (
        re.compile(r"Failed to resolve packages?[:\s][^\r\n]*", re.IGNORECASE),
        "resolve-failed",
    ),
    (
        re.compile(r"An error occurred while resolving packages[:\s][^\r\n]*", re.IGNORECASE),
        "resolve-failed",
    ),
    (
        re.compile(r"Cannot find package[:\s]+[^\r\n]*", re.IGNORECASE),
        "package-not-found",
    ),
    (
        re.compile(r"Unable to (?:add|resolve|update) package[^\r\n]*", re.IGNORECASE),
        "package-add-failed",
    ),
    (
        re.compile(
            r"Package\s*\[?[A-Za-z0-9_.\-]+(?:@[^\s\]\r\n]+)?\]?[^\r\n]*?"
            r"(?:cannot be found|is not available|was not found|does not exist)[^\r\n]*",
            re.IGNORECASE,
        ),
        "package-not-found",
    ),
    (
        re.compile(r"\[Package Manager\][^\r\n]*", re.IGNORECASE),
        "package-manager",
    ),
    (
        re.compile(r"Package Manager[^\r\n]*?(?:Error|failed)[^\r\n]*", re.IGNORECASE),
        "package-manager",
    ),
)

# The bracketed [Package Manager] tag also fronts routine progress chatter, so a
# generic match only counts as an error when the line says something went wrong.
_PACKAGE_FAILURE_WORDS = re.compile(
    r"error|fail|cannot|could not|unable|unresolved|not available|not found", re.IGNORECASE
)
_GENERIC_PACKAGE_KINDS = {"package-manager"}


def parse_package_errors(log_text: str) -> list[dict[str, Any]]:
    """Extract UPM resolution failures from a Unity Editor log."""

    text = _as_text(log_text)
    if not text:
        return []

    out: dict[tuple[Any, ...], dict[str, Any]] = {}
    for kind, match, line_text in _scan_claimed_lines(text, _PACKAGE_ERROR_PATTERNS):
        message = (match.group(0) or "").strip()
        if kind in _GENERIC_PACKAGE_KINDS and not _PACKAGE_FAILURE_WORDS.search(line_text):
            continue
        package_match = _PACKAGE_ID_RE.search(line_text)
        package = package_match.group(1) if package_match else None
        entry = {
            "kind": kind,
            "package": package,
            "message": message,
            "raw": line_text,
            "occurrences": 1,
        }
        key = (kind, package, line_text)
        existing = out.get(key)
        if existing is None:
            out[key] = entry
        else:
            existing["occurrences"] += 1
    return list(out.values())


def summarize_log(log_text: str) -> dict[str, Any]:
    """Roll the three parsers into counts plus the findings themselves."""

    errors = parse_compile_errors(log_text)
    references = parse_missing_references(log_text)
    packages = parse_package_errors(log_text)

    codes: dict[str, int] = {}
    for error in errors:
        code = str(error.get("code") or "UNKNOWN")
        codes[code] = codes.get(code, 0) + 1

    kinds: dict[str, int] = {}
    for reference in references:
        kind = str(reference.get("kind") or "unknown")
        kinds[kind] = kinds.get(kind, 0) + int(reference.get("occurrences") or 1)

    return {
        "compileErrorCount": len(errors),
        "compileErrorCodes": codes,
        "compileErrors": errors,
        "missingReferenceCount": len(references),
        "missingReferenceOccurrences": sum(int(r.get("occurrences") or 1) for r in references),
        "missingReferenceKinds": kinds,
        "missingReferences": references,
        "packageErrorCount": len(packages),
        "packageErrors": packages,
        "clean": not errors and not packages,
    }


# ---------------------------------------------------------------------------
# Part 3 -- repair recipes. `classify_error` is pure; the appliers touch disk.
# ---------------------------------------------------------------------------

RECIPES: dict[str, str] = {
    "delete-file": (
        "Delete the offending source file. For duplicate assembly-level attributes "
        "(CS0579) the file named in the error is redundant metadata, not gameplay code."
    ),
    "dedupe-type": (
        "Remove or rename one of two colliding definitions (CS0101 duplicate type, "
        "CS0111 duplicate member) produced by decompiling overlapping assemblies."
    ),
    "resolve-missing-type": (
        "Resolve an unknown type (CS0246): copy the shipped assembly that defines it "
        "into Assets/Plugins, or add the UPM package that provides it to the manifest."
    ),
    "remap-guid": (
        "Repoint a MonoBehaviour whose script GUID resolves to nothing, using the "
        "AuxiliaryFiles/path_id_map.json emitted alongside the ripped project."
    ),
    "relax-package": (
        "Loosen or drop an unresolvable package dependency in Packages/manifest.json "
        "so the project can finish resolving."
    ),
}

# Codes that make deleting the named file the correct fix. Kept as a set so the
# recipe generalises: it catches ILSpy's Properties/AssemblyInfo.cs without ever
# naming it, and would equally catch a duplicated attribute file from any source.
_DELETE_FILE_CODES = frozenset({"CS0579"})
_DEDUPE_TYPE_CODES = frozenset({"CS0101", "CS0111"})
_MISSING_TYPE_CODES = frozenset({"CS0246", "CS0234"})

_REMAP_GUID_KINDS = frozenset({"missing-script", "missing-guid", "script-layout-mismatch"})
_RELAX_PACKAGE_KINDS = frozenset(
    {"resolve-failed", "package-not-found", "package-add-failed", "package-manager"}
)


def classify_error(error: dict[str, Any]) -> str | None:
    """Map one finding to a recipe id, or ``None`` when nothing here applies.

    Accepts any of the three finding shapes -- compile error (``code``), missing
    reference (``kind``), package error (``kind``) -- because the repair loop
    classifies them through a single path. Never raises.
    """

    if not isinstance(error, dict):
        return None

    code = error.get("code")
    if isinstance(code, str):
        code = code.strip().upper()
        if code in _DELETE_FILE_CODES:
            return "delete-file"
        if code in _DEDUPE_TYPE_CODES:
            return "dedupe-type"
        if code in _MISSING_TYPE_CODES:
            return "resolve-missing-type"

    kind = error.get("kind")
    if isinstance(kind, str):
        kind = kind.strip().lower()
        if kind in _REMAP_GUID_KINDS:
            return "remap-guid"
        if kind in _RELAX_PACKAGE_KINDS:
            return "relax-package"

    return None


def _resolve_in_assets(project_path: Path, raw_path: str) -> tuple[Path | None, str | None]:
    """Resolve ``raw_path`` to a real path under ``<project>/Assets``.

    Returns ``(path, refusal_reason)``. Symlinks are resolved before the
    containment check, so a link pointing out of the project is refused.
    """

    project = Path(project_path).resolve()
    assets = (project / "Assets").resolve()
    candidate = Path(str(raw_path).replace("\\", "/"))
    if not candidate.is_absolute():
        candidate = project / candidate
    try:
        resolved = candidate.resolve()
    except OSError as exc:
        return None, f"cannot resolve path: {exc}"
    if resolved == assets or not resolved.is_relative_to(assets):
        return None, f"refusing to touch a path outside {assets}: {resolved}"
    return resolved, None


def apply_delete_file(project_path: Path, error: dict[str, Any]) -> dict[str, Any]:
    """Delete the source file named by a ``delete-file`` error, plus its ``.meta``.

    Guarded three ways, because this is the only destructive recipe implemented:
    the error must classify as ``delete-file`` (so an arbitrary error can never be
    turned into a deletion), the path must come from the error itself, and the
    resolved path must live under ``<project>/Assets``.
    """

    recipe = "delete-file"
    if classify_error(error) != recipe:
        return {
            "status": "refused",
            "recipe": recipe,
            "reason": f"error does not classify as {recipe}: code={error.get('code') if isinstance(error, dict) else None}",
        }

    raw_path = error.get("file") if isinstance(error, dict) else None
    if not raw_path:
        return {
            "status": "skipped",
            "recipe": recipe,
            "reason": "error carries no file path to delete",
        }

    target, refusal = _resolve_in_assets(Path(project_path), str(raw_path))
    if target is None:
        return {"status": "refused", "recipe": recipe, "reason": refusal, "path": str(raw_path)}
    if not target.is_file():
        return {
            "status": "skipped",
            "recipe": recipe,
            "reason": "file does not exist (already removed?)",
            "path": str(target),
        }

    deleted: list[str] = []
    try:
        target.unlink()
        deleted.append(str(target))
    except OSError as exc:
        return {"status": "error", "recipe": recipe, "reason": str(exc), "path": str(target)}

    meta = target.with_name(target.name + ".meta")
    if meta.is_file():
        try:
            meta.unlink()
            deleted.append(str(meta))
        except OSError:
            pass  # A stale .meta is harmless; Unity prunes it on the next import.

    return {
        "status": "applied",
        "recipe": recipe,
        "path": str(target),
        "deleted": deleted,
        "reason": f"{error.get('code')}: {error.get('message')}",
    }


# -- Unimplemented recipes ---------------------------------------------------
# These return `not-implemented` on purpose. Each needs evidence this module does
# not have (the shipped DLL set, the AuxiliaryFiles GUID map, the original
# manifest), and a stub that silently "succeeded" would make the repair loop
# report convergence it never achieved.


def apply_dedupe_type(project_path: Path, error: dict[str, Any]) -> dict[str, Any]:
    """NOT IMPLEMENTED. Resolving a duplicate type needs both definitions compared."""

    return {
        "status": "not-implemented",
        "recipe": "dedupe-type",
        "reason": (
            "needs both colliding declarations located and compared before one can be "
            "removed; deleting the wrong one silently drops gameplay code"
        ),
        "error": error,
    }


def apply_resolve_missing_type(
    project_path: Path,
    error: dict[str, Any],
    *,
    shipped_dll_dirs: list[Path] | None = None,
) -> dict[str, Any]:
    """NOT IMPLEMENTED. Needs the shipped Managed/ DLL set to resolve against."""

    return {
        "status": "not-implemented",
        "recipe": "resolve-missing-type",
        "reason": (
            "needs a shipped assembly index to decide between copying a DLL into "
            "Assets/Plugins and adding a UPM package; no index is wired in yet"
        ),
        "shippedDllDirs": [str(p) for p in (shipped_dll_dirs or [])],
        "error": error,
    }


def apply_remap_guid(
    project_path: Path,
    reference: dict[str, Any],
    *,
    path_id_map: Path | None = None,
) -> dict[str, Any]:
    """NOT IMPLEMENTED. Needs ``AuxiliaryFiles/path_id_map.json`` from the rip."""

    return {
        "status": "not-implemented",
        "recipe": "remap-guid",
        "reason": (
            "needs AuxiliaryFiles/path_id_map.json to map a dead script GUID onto a "
            "recovered MonoScript; rewriting scene YAML without it would corrupt scenes"
        ),
        "pathIdMap": str(path_id_map) if path_id_map else None,
        "reference": reference,
    }


def apply_relax_package(project_path: Path, error: dict[str, Any]) -> dict[str, Any]:
    """NOT IMPLEMENTED. Editing the manifest changes what the project *is*."""

    return {
        "status": "not-implemented",
        "recipe": "relax-package",
        "reason": (
            "dropping a dependency from Packages/manifest.json changes the recovered "
            "project's declared surface; needs an explicit policy decision, not a default"
        ),
        "error": error,
    }


RECIPE_APPLIERS: dict[str, Callable[..., dict[str, Any]]] = {
    "delete-file": apply_delete_file,
    "dedupe-type": apply_dedupe_type,
    "resolve-missing-type": apply_resolve_missing_type,
    "remap-guid": apply_remap_guid,
    "relax-package": apply_relax_package,
}

IMPLEMENTED_RECIPES: frozenset[str] = frozenset({"delete-file"})


# ---------------------------------------------------------------------------
# Part 4 -- orchestration. The only functions here that spawn a process.
# ---------------------------------------------------------------------------

_VALIDATE_CLAIM = (
    "proves only that the Editor opened this project in batchmode and reported the compile "
    "errors, scene opens, and missing script counts recorded above; it does not prove "
    "byte-identity with the shipped game, correct gameplay behavior, or that runtime-loaded "
    "(Resources/Addressables) content is intact"
)


def _read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ""


def _require_editor(editor: Path | None) -> Path:
    if editor is None:
        raise ToolchainError("unity-editor-missing", detail="no Unity Editor executable was provided")
    resolved = Path(editor).expanduser()
    if not resolved.is_file() or not os.access(resolved, os.X_OK):
        raise ToolchainError(
            "unity-editor-missing",
            detail=f"not an executable Unity Editor: {resolved}",
        )
    return resolved


def validate_unity_project(
    project_path: Path,
    *,
    editor: Path,
    timeout: int = 3600,
    log_dir: Path | None = None,
) -> dict[str, Any]:
    """Open a project in batchmode, run the injected probe, and report what broke.

    Two independent evidence sources are merged: the probe's JSON report (scene
    opens, root counts, missing-script counts) and the Editor log (compile errors,
    package failures). When compilation fails the Editor never invokes
    ``-executeMethod``, so ``validatorRan`` is false and the log carries the whole
    story -- which is the normal, expected path on a first pass.
    """

    project = Path(project_path).resolve()
    editor_path = _require_editor(editor)

    if not project.is_dir() or not (project / "Assets").is_dir():
        return {
            "schema": "agentdecompile.unity-validate.v1",
            "status": "error",
            "clean": False,
            "projectPath": str(project),
            "reason": "not a Unity project: no Assets/ directory under project path",
            "claimBoundary": "nothing was validated; the Editor was never launched",
        }

    report_path = validator_report_path(project)
    try:
        report_path.unlink()  # a stale report from a previous attempt would lie
    except OSError:
        pass
    report_path.parent.mkdir(parents=True, exist_ok=True)

    logs_dir = Path(log_dir) if log_dir is not None else project / "Logs"
    logs_dir.mkdir(parents=True, exist_ok=True)
    log_path = logs_dir / f"adrecovery-validate-{time.strftime('%Y%m%d-%H%M%S')}.log"

    validator_path = install_validator(project)

    previous_env = os.environ.get(VALIDATOR_OUT_ENV)
    os.environ[VALIDATOR_OUT_ENV] = str(report_path)
    started = time.monotonic()
    timed_out = False
    proc = None
    try:
        proc = run_unity_batchmode(
            editor_path,
            project,
            execute_method=VALIDATOR_METHOD,
            log_file=log_path,
            timeout=timeout,
        )
    except FileNotFoundError as exc:
        raise ToolchainError("unity-editor-missing", detail=str(exc)) from exc
    except subprocess.TimeoutExpired:
        # A hung import is a finding, not a crash: the partial log still parses.
        timed_out = True
    finally:
        if previous_env is None:
            os.environ.pop(VALIDATOR_OUT_ENV, None)
        else:
            os.environ[VALIDATOR_OUT_ENV] = previous_env
    duration = time.monotonic() - started

    log_text = _read_text(log_path)
    if proc is not None:
        log_text = "\n".join([log_text, proc.stdout or "", proc.stderr or ""])
    summary = summarize_log(log_text)

    report: dict[str, Any] | None = None
    if report_path.is_file():
        try:
            report = json.loads(_read_text(report_path))
        except (json.JSONDecodeError, ValueError):
            report = None
    validator_ran = isinstance(report, dict)

    scene_detail = list(report.get("scenes") or []) if validator_ran else []
    scenes = {
        "source": (report.get("sceneSource") if validator_ran else None),
        "total": int(report.get("sceneTotal") or 0) if validator_ran else 0,
        "opened": int(report.get("scenesOpened") or 0) if validator_ran else 0,
        "missingScriptTotal": int(report.get("missingScriptTotal") or 0) if validator_ran else 0,
        "detail": scene_detail,
    }

    compile_state = (report.get("compile") if validator_ran else None) or {}
    compilation_failed = compile_state.get("compilationFailed")
    if compilation_failed is None and not validator_ran:
        # The Editor declining to run -executeMethod *is* the compile-failure signal.
        compilation_failed = True if summary["compileErrorCount"] else None

    clean = bool(
        validator_ran
        and summary["compileErrorCount"] == 0
        and not compilation_failed
        and scenes["opened"] == scenes["total"]
    )

    if timed_out:
        status = "timeout"
    elif clean:
        status = "complete"
    else:
        status = "failed"

    return {
        "schema": "agentdecompile.unity-validate.v1",
        "status": status,
        "clean": clean,
        "projectPath": str(project),
        "editor": str(editor_path),
        "returnCode": (proc.returncode if proc is not None else None),
        "durationSeconds": round(duration, 2),
        "timedOut": timed_out,
        "validatorRan": validator_ran,
        "validatorPath": str(validator_path),
        "validatorMethod": VALIDATOR_METHOD,
        "reportPath": str(report_path) if validator_ran else None,
        "logPath": str(log_path),
        "unityVersion": (report.get("unityVersion") if validator_ran else None),
        "scenes": scenes,
        "compile": {
            "errorCount": summary["compileErrorCount"],
            "errorCodes": summary["compileErrorCodes"],
            "errors": summary["compileErrors"],
            "compilationFailed": compilation_failed,
            "editorAssemblyCount": compile_state.get("editorAssemblyCount"),
            "playerAssemblyCount": compile_state.get("playerAssemblyCount"),
        },
        "missingReferenceCount": summary["missingReferenceCount"],
        "missingReferences": summary["missingReferences"],
        "packageErrorCount": summary["packageErrorCount"],
        "packageErrors": summary["packageErrors"],
        "claimBoundary": _VALIDATE_CLAIM,
    }


def _findings(validation: dict[str, Any]) -> list[dict[str, Any]]:
    """Every classifiable finding from one validation, compile errors first."""

    findings: list[dict[str, Any]] = []
    findings.extend((validation.get("compile") or {}).get("errors") or [])
    findings.extend(validation.get("missingReferences") or [])
    findings.extend(validation.get("packageErrors") or [])
    return findings


def repair_unity_project(
    project_path: Path,
    *,
    editor: Path,
    max_attempts: int = 3,
    timeout: int = 3600,
) -> dict[str, Any]:
    """Validate, repair what has an implemented recipe, re-validate, repeat.

    Stops on the first of: a clean validation, no finding matching an implemented
    recipe, a compile-error count that failed to *decrease* since the previous
    attempt, or ``max_attempts`` validations. The non-convergence guard exists
    because a recipe that fires without helping would otherwise loop until the
    timeout -- burning an hour per attempt on a project that cannot be fixed here.
    """

    project = Path(project_path).resolve()
    attempts: list[dict[str, Any]] = []
    previous_count: int | None = None
    disposition = "max-attempts"
    unverified_repairs = False
    final: dict[str, Any] | None = None

    for attempt_index in range(1, max(1, int(max_attempts)) + 1):
        validation = validate_unity_project(project, editor=editor, timeout=timeout)
        final = validation
        error_count = int((validation.get("compile") or {}).get("errorCount") or 0)

        record: dict[str, Any] = {
            "attempt": attempt_index,
            "status": validation.get("status"),
            "errorCount": error_count,
            "missingReferenceCount": int(validation.get("missingReferenceCount") or 0),
            "packageErrorCount": int(validation.get("packageErrorCount") or 0),
            "scenesOpened": (validation.get("scenes") or {}).get("opened"),
            "scenesTotal": (validation.get("scenes") or {}).get("total"),
            "logPath": validation.get("logPath"),
            "recipesFired": {},
            "actions": [],
            "unfixable": [],
        }

        if validation.get("status") in {"error", "timeout"}:
            disposition = str(validation.get("status"))
            attempts.append(record)
            break

        if validation.get("clean"):
            disposition = "clean"
            unverified_repairs = False
            attempts.append(record)
            break

        if previous_count is not None and error_count >= previous_count:
            disposition = "non-convergent"
            record["note"] = (
                f"compile errors did not decrease ({previous_count} -> {error_count}); "
                "stopping rather than looping on an unfixable error"
            )
            attempts.append(record)
            break

        fired: dict[str, int] = {}
        actions: list[dict[str, Any]] = []
        unfixable: list[dict[str, Any]] = []
        applied_any = False

        for finding in _findings(validation):
            recipe = classify_error(finding)
            if recipe is None:
                unfixable.append({"reason": "no recipe matches this finding", "finding": finding})
                continue
            if recipe not in IMPLEMENTED_RECIPES:
                unfixable.append(
                    {
                        "reason": f"recipe '{recipe}' is not implemented",
                        "recipe": recipe,
                        "finding": finding,
                    }
                )
                continue
            applier = RECIPE_APPLIERS[recipe]
            result = applier(project, finding)
            actions.append(result)
            fired[recipe] = fired.get(recipe, 0) + 1
            if result.get("status") == "applied":
                applied_any = True
            else:
                unfixable.append(
                    {
                        "reason": f"recipe '{recipe}' returned {result.get('status')}: {result.get('reason')}",
                        "recipe": recipe,
                        "finding": finding,
                    }
                )

        record["recipesFired"] = fired
        record["actions"] = actions
        record["unfixable"] = unfixable
        attempts.append(record)

        if not applied_any:
            disposition = "no-recipe"
            break

        # A repair landed but has not been re-validated yet; only the next loop
        # iteration turns it into evidence.
        unverified_repairs = True
        previous_count = error_count
    else:
        disposition = "max-attempts"

    final_errors = list(((final or {}).get("compile") or {}).get("errors") or [])
    unfixed = [error for error in final_errors if classify_error(error) not in IMPLEMENTED_RECIPES]
    unimplemented: dict[str, int] = {}
    for error in unfixed:
        recipe = classify_error(error) or "unclassified"
        unimplemented[recipe] = unimplemented.get(recipe, 0) + 1

    if disposition == "clean":
        status = "complete"
    elif disposition in {"error", "timeout"}:
        status = "error"
    else:
        status = "failed"

    return {
        "schema": "agentdecompile.unity-repair.v1",
        "status": status,
        "disposition": disposition,
        "projectPath": str(project),
        "editor": str(Path(editor)),
        "maxAttempts": int(max_attempts),
        "attemptCount": len(attempts),
        "attempts": attempts,
        "finalErrorCount": int(((final or {}).get("compile") or {}).get("errorCount") or 0),
        "unfixedErrorCount": len(unfixed),
        "unfixedErrors": unfixed,
        "unimplementedRecipeCounts": unimplemented,
        "recipes": RECIPES,
        "implementedRecipes": sorted(IMPLEMENTED_RECIPES),
        "unverifiedRepairs": unverified_repairs,
        "finalValidation": final,
        "claimBoundary": (
            "records what the batchmode Editor reported before and after each applied repair; "
            + _VALIDATE_CLAIM
            + ". Repairs applied on the final attempt are unverified when unverifiedRepairs is true"
        ),
    }
