"""Produce a verified byte-exact, compilable reconstruction of a PE binary.

This is not semantic recovery. A ``_emit`` body is machine code wrapped in C.
Store path, raw image, and output directory are required. There is no
product-binary default and no implicit ``--all-x86-pe`` list.
"""

from __future__ import annotations

import concurrent.futures as cf
import json
import pathlib
import struct
import subprocess
import tempfile
import time

from .extract import slugify
from .store import connect

BATCH = 500


def pe_va_mapper(raw: bytes):
    """Return (va->file offset) for a PE image, or None if not a PE."""
    if raw[:2] != b"MZ":
        return None
    pe = struct.unpack_from("<I", raw, 0x3C)[0]
    if raw[pe : pe + 4] != b"PE\0\0":
        return None
    nsec = struct.unpack_from("<H", raw, pe + 6)[0]
    opt = struct.unpack_from("<H", raw, pe + 20)[0]
    base = struct.unpack_from("<I", raw, pe + 24 + 28)[0]
    secs = []
    for i in range(nsec):
        o = pe + 24 + opt + i * 40
        vsize, vaddr, rsize, roff = struct.unpack_from("<IIII", raw, o + 8)
        secs.append((vaddr, max(vsize, rsize), roff))

    def va2off(va: int):
        r = va - base
        for vaddr, size, roff in secs:
            if vaddr <= r < vaddr + size:
                return roff + (r - vaddr)
        return None

    return va2off


def emit_tu(funcs: list[tuple[int, bytes]]) -> str:
    """One translation unit holding many functions, each its own COMDAT."""
    out = [
        "/* Byte-exact reconstruction. Each function is emitted as its original",
        " * machine code so that the compiled output is provably identical to the",
        " * shipped image. Generated by exact_corpus — do not edit.",
        " */",
    ]
    for addr, data in funcs:
        out.append(f'extern "C" __declspec(naked) void F_{addr:08x}(void){{__asm{{')
        out += [f"_emit 0x{b:02x}" for b in data]
        out.append("}}")
    return "\n".join(out) + "\n"


def coff_functions(obj: bytes, prefix: str = "_F_") -> dict[str, bytes]:
    """Extract every ``_F_xxxxxxxx`` function's bytes from a COFF object."""
    _machine, nsec, _, symptr, nsym = struct.unpack_from("<HHIII", obj, 0)
    strtab_off = symptr + nsym * 18
    strtab = obj[strtab_off:]

    sections = []
    for i in range(nsec):
        o = 20 + i * 40
        raw_size, raw_ptr = struct.unpack_from("<II", obj, o + 16)
        sections.append((raw_ptr, raw_size))

    out: dict[str, bytes] = {}
    i = 0
    while i < nsym:
        o = symptr + i * 18
        name_raw = obj[o : o + 8]
        value, secnum = struct.unpack_from("<IH", obj, o + 8)
        naux = obj[o + 17]
        if name_raw[:4] == b"\0\0\0\0":
            off = struct.unpack_from("<I", name_raw, 4)[0]
            end = strtab.find(b"\0", off)
            name = strtab[off:end].decode("latin1", "replace")
        else:
            name = name_raw.rstrip(b"\0").decode("latin1", "replace")
        if name.startswith(prefix) and 1 <= secnum <= len(sections):
            raw_ptr, raw_size = sections[secnum - 1]
            if raw_ptr:
                out[name] = obj[raw_ptr + value : raw_ptr + raw_size]
        i += 1 + naux
    return out


def verify_batch(
    funcs: list[tuple[int, bytes]],
    *,
    compile_script: pathlib.Path | str | None = None,
) -> tuple[int, int, list[int]]:
    """Compile a batch and confirm each function's bytes. Returns (ok, total, failed)."""
    script = pathlib.Path(compile_script) if compile_script else None
    if script is None or not script.exists():
        return 0, len(funcs), [a for a, _ in funcs]
    with tempfile.TemporaryDirectory() as td:
        tdp = pathlib.Path(td)
        cpp, obj = tdp / "b.cpp", tdp / "b.obj"
        cpp.write_text(emit_tu(funcs))
        subprocess.run([str(script), str(cpp), str(obj)], capture_output=True, text=True)
        if not obj.exists():
            return 0, len(funcs), [a for a, _ in funcs]
        try:
            got = coff_functions(obj.read_bytes())
        except Exception:
            return 0, len(funcs), [a for a, _ in funcs]
        ok, failed = 0, []
        for addr, data in funcs:
            blob = got.get(f"_F_{addr:08x}")
            if blob is not None and blob[: len(data)] == data:
                ok += 1
            else:
                failed.append(addr)
        return ok, len(funcs), failed


def process(
    repo_path: str,
    outdir: pathlib.Path | str,
    store_path: pathlib.Path | str,
    raw_path: pathlib.Path | str,
    *,
    workers: int = 10,
    compile_script: pathlib.Path | str | None = None,
    verify: bool = True,
) -> dict:
    """Emit byte-exact C for *repo_path* under *outdir*. All paths required."""
    con = connect(store_path)
    slug = slugify(repo_path)
    src = pathlib.Path(raw_path)
    if not src.exists():
        return {"repo_path": repo_path, "error": f"raw image not exported: {src}"}
    raw = src.read_bytes()
    va2off = pe_va_mapper(raw)
    if va2off is None:
        return {"repo_path": repo_path, "error": "not a PE image"}

    row = con.execute("SELECT id FROM binary WHERE repo_path=?", (repo_path,)).fetchone()
    if row is None:
        return {"repo_path": repo_path, "error": "not in database"}

    funcs = []
    skipped = 0
    for r in con.execute(
        "SELECT addr, size FROM func WHERE binary_id=? AND n_instr>0 AND size>0",
        (row["id"],),
    ):
        off = va2off(r["addr"])
        if off is None or off + r["size"] > len(raw):
            skipped += 1
            continue
        funcs.append((r["addr"], raw[off : off + r["size"]]))

    dest = pathlib.Path(outdir)
    dest.mkdir(parents=True, exist_ok=True)
    batches = [funcs[i : i + BATCH] for i in range(0, len(funcs), BATCH)]
    t0 = time.time()
    ok = total = 0
    failed_all: list[int] = []
    if verify and compile_script:
        with cf.ThreadPoolExecutor(max_workers=workers) as ex:
            for o, t, f in ex.map(
                lambda b: verify_batch(b, compile_script=compile_script),
                batches,
            ):
                ok += o
                total += t
                failed_all += f
    else:
        total = len(funcs)

    srcdir = dest / slug
    srcdir.mkdir(parents=True, exist_ok=True)
    for i, batch in enumerate(batches):
        (srcdir / f"part{i:04d}.cpp").write_text(emit_tu(batch))

    el = time.time() - t0
    return {
        "repo_path": repo_path,
        "functions": len(funcs),
        "skipped_no_file_offset": skipped,
        "byte_exact": ok,
        "failed": len(failed_all),
        "rate": round(ok / max(total, 1), 6),
        "seconds": round(el, 1),
        "ms_per_function": round(el / max(len(funcs), 1) * 1000, 2),
        "sources": str(srcdir),
        "failed_sample": [f"0x{a:x}" for a in failed_all[:20]],
        "verified": bool(verify and compile_script),
    }


def write_coverage(outdir: pathlib.Path | str, results: list[dict]) -> pathlib.Path:
    dest = pathlib.Path(outdir)
    dest.mkdir(parents=True, exist_ok=True)
    path = dest / "_coverage.json"
    path.write_text(json.dumps(results, indent=1), encoding="utf-8")
    return path
