"""Emit a Decomp Atlas JSON bundle from a corpus identity store.

One Atlas project file describes one build. Cross-build identity is carried
in the name and in ``crossBuild`` metadata. All writers take an explicit
``out_root``; there is no default atlas output tree.
"""

from __future__ import annotations

import argparse
import json
import math
import pathlib
import sqlite3
import time

from . import store

KNOWLEDGE_DB = pathlib.Path("ghidra_knowledge.sqlite")

VECTOR_FIELDS = [
    "size", "n_instr", "n_blocks", "n_edges", "cyclomatic",
    "n_callees", "param_count", "stack_frame_size",
]


def atlas_target(arch: str | None, platform: str | None = None) -> str:
    """Map recorded binary metadata to an architecture target the Atlas accepts.

    This must never use a console as a placeholder. A previous constant wrote
    ``gba`` for every PE, ELF, Mach-O, and XBE and leaked a handheld platform
    into the UI and generated prompts.
    """
    value = (arch or "").strip().lower().replace("-", "_")
    return {
        "x86": "x86",
        "i386": "x86",
        "x86_64": "x86_64",
        "amd64": "x86_64",
        "arm": "arm",
        "aarch64": "aarch64",
        "arm64": "aarch64",
        "powerpc": "ppc",
        "ppc": "ppc",
    }.get(value, "unknown")


ATLAS_YAML = """\
# Generated by export_atlas_db.py — points a Decomp Atlas at this corpus.
# Every field below is required by the Atlas config schema.
global:
  projectRoot: {root}
  mapFilePath: {root}/project.map
  promptsDir: ./prompts
  nonMatchingAsmFolders:
    - asm
  outputDir: .
  target: {target}
  compilerScript: 'true'
  getContextScript: 'true'
  maxRetries: 1
plugins:
  integrator:
    enable: false
    integratorModule: './integrator.mjs'
"""


def _program(repo_path: str) -> str:
    return repo_path.rstrip("/").split("/")[-1]


def _hex_width(con: sqlite3.Connection, program: str) -> int:
    row = con.execute(
        "SELECT entry_hex FROM func_knowledge WHERE program=? LIMIT 1",
        (program,)).fetchone()
    return len(row[0]) if row else 8


def _knowledge(
    program: str,
    addrs: list[int] | None,
    want_c: bool,
    want_asm: bool,
    *,
    knowledge_db: pathlib.Path | None = None,
) -> dict[int, dict]:
    kb = pathlib.Path(knowledge_db) if knowledge_db is not None else pathlib.Path(KNOWLEDGE_DB)
    if not kb.exists() or not (want_c or want_asm):
        return {}
    cols = []
    if want_c:
        cols.append("decompiled")
    if want_asm:
        cols.append("asm")
    con = sqlite3.connect(f"file:{kb}?mode=ro", uri=True)
    out: dict[int, dict] = {}

    def absorb(entry_hex: str, values: tuple) -> None:
        try:
            addr = int(entry_hex, 16)
        except (TypeError, ValueError):
            return
        rec = {}
        vals = list(values)
        if want_c:
            rec["c"] = vals.pop(0)
        if want_asm:
            rec["asm"] = vals.pop(0)
        out[addr] = rec

    try:
        sel = ", ".join(cols)
        if addrs is None:
            for row in con.execute(
                    f"SELECT entry_hex, {sel} FROM func_knowledge WHERE program=?",
                    (program,)):
                absorb(row[0], row[1:])
        else:
            width = _hex_width(con, program)
            q = (f"SELECT entry_hex, {sel} FROM func_knowledge "
                 "WHERE program=? AND entry_hex=?")
            for addr in addrs:
                row = con.execute(q, (program, f"{addr:0{width}x}")).fetchone()
                if row is not None:
                    absorb(row[0], row[1:])
    except sqlite3.Error:
        pass
    con.close()
    return out


def _vector(row: dict) -> list[float]:
    vec = []
    for f in VECTOR_FIELDS:
        v = row.get(f) or 0
        try:
            vec.append(math.log1p(float(v)))
        except (TypeError, ValueError):
            vec.append(0.0)
    return vec


def build(
    repo_path: str,
    max_functions: int | None = None,
    with_asm: bool = True,
    with_c: bool = True,
    *,
    con: sqlite3.Connection | None = None,
    db_path: pathlib.Path | str | None = None,
    knowledge_db: pathlib.Path | None = None,
) -> dict:
    if con is None:
        if db_path is None:
            raise ValueError("build() requires con or db_path")
        con = store.connect(db_path)
    b = con.execute(
        "SELECT id, slug, repo_path, arch, bits, platform, func_count FROM binary "
        "WHERE repo_path=?", (repo_path,)).fetchone()
    if b is None:
        raise ValueError(f"no such binary: {repo_path}")
    bid, slug = b["id"], b["slug"]
    program = _program(repo_path)

    names: dict[int, tuple[str, str]] = {}
    try:
        for addr, name, tier in con.execute(
                "SELECT i.addr, n.name, n.tier_name FROM identity i "
                "JOIN logical_name n ON n.logical_id = i.logical_id "
                "WHERE i.binary_id=?", (bid,)):
            names[addr] = (name, tier)
    except sqlite3.Error:
        names = {}

    logical: dict[int, int] = {
        addr: lid for addr, lid in con.execute(
            "SELECT addr, logical_id FROM identity WHERE binary_id=?", (bid,))}

    reach: dict[int, int] = {}
    if logical:
        wanted = set(logical.values())
        seen: dict[int, set[int]] = {}
        for other_bid, lid in con.execute(
                "SELECT binary_id, logical_id FROM identity"):
            if lid in wanted:
                seen.setdefault(lid, set()).add(other_bid)
        reach = {lid: len(bins) for lid, bins in seen.items()}

    calls: dict[int, list[int]] = {}
    for caller, callee in con.execute(
            "SELECT caller_addr, callee_addr FROM calledge WHERE binary_id=?", (bid,)):
        calls.setdefault(caller, []).append(callee)

    def fid(addr: int) -> str:
        return f"{slug}::{addr:08x}"

    rows = [dict(r) for r in con.execute(
        "SELECT addr, name, size, n_instr, n_blocks, n_edges, cyclomatic, "
        "       n_callees, param_count, stack_frame_size, signature, "
        "       source_file, object_file "
        "FROM func WHERE binary_id=? AND size>0 AND n_instr>0 "
        "ORDER BY addr", (bid,))]

    kept_ids: set[str] | None = None
    if max_functions is not None and len(rows) > max_functions:
        rows.sort(key=lambda r: (r.get("n_instr") or 0, r.get("size") or 0),
                  reverse=True)
        rows = sorted(rows[:max_functions], key=lambda r: r["addr"])
        kept_ids = {fid(r["addr"]) for r in rows}

    know = _knowledge(
        program,
        [r["addr"] for r in rows] if kept_ids is not None else None,
        want_c=with_c, want_asm=with_asm, knowledge_db=knowledge_db)

    funcs, vectors = [], []
    for row in rows:
        addr = row["addr"]
        k = know.get(addr, {})
        resolved, tier = names.get(addr, (None, None))
        lid = logical.get(addr)
        edges = [fid(a) for a in calls.get(addr, [])]
        if kept_ids is not None:
            edges = [e for e in edges if e in kept_ids]
        doc = {
            "id": fid(addr),
            "name": resolved or row["name"] or f"FUN_{addr:08x}",
            "romAddress": addr,
            "asmCode": k.get("asm") or "",
            "asmModulePath": row.get("source_file") or "unattributed",
            "callsFunctions": edges,
        }
        if k.get("c"):
            doc["cCode"] = k["c"]
            doc["cModulePath"] = row.get("source_file") or "unattributed"
        doc["crossBuild"] = {
            "logicalId": lid,
            "buildsReached": reach.get(lid, 1 if lid else 0),
            "nameTier": tier,
            "signature": row.get("signature"),
            "objectFile": row.get("object_file"),
        }
        funcs.append(doc)
        vectors.append({"id": doc["id"], "embedding": _vector(row)})

    meta = {
        "contentHashes": {},
        "source": "agentdecompile corpus store",
        "binary": repo_path,
        "arch": b["arch"],
        "bits": b["bits"],
        "generatedAt": time.time(),
    }
    if kept_ids is not None:
        meta["truncated"] = {"maxFunctions": max_functions,
                             "selection": "largest-first by n_instr",
                             "totalFunctions": b["func_count"]}
    if not with_asm:
        meta["omitted"] = meta.get("omitted", []) + ["asmCode"]
    if not with_c:
        meta["omitted"] = meta.get("omitted", []) + ["cCode"]

    target = atlas_target(b["arch"], b["platform"])
    return {
        "version": 1,
        "platform": target,
        "decompFunctions": funcs,
        "vectors": vectors,
        "indexMetadata": meta,
    }


def write(
    repo_path: str,
    out_root: pathlib.Path,
    max_functions: int | None = None,
    with_asm: bool = True,
    with_c: bool = True,
    *,
    con: sqlite3.Connection | None = None,
    db_path: pathlib.Path | str | None = None,
    knowledge_db: pathlib.Path | None = None,
) -> pathlib.Path:
    dump = build(
        repo_path, max_functions=max_functions,
        with_asm=with_asm, with_c=with_c,
        con=con, db_path=db_path, knowledge_db=knowledge_db,
    )
    slug = repo_path.strip("/").replace("/", "__")
    root = pathlib.Path(out_root) / slug
    root.mkdir(parents=True, exist_ok=True)
    out = root / "atlas-db.json"
    tmp = out.with_suffix(".json.partial")
    tmp.write_text(json.dumps(dump))
    tmp.replace(out)
    # Atlas loaders historically looked for this filename; keep a copy.
    atlas_alias = root / "mizuchi-db.json"
    if not atlas_alias.exists():
        atlas_alias.write_text(out.read_text())
    (root / "project.map").write_text("\n".join(
        f"{f['romAddress']:08x} {f['name']}" for f in dump["decompFunctions"]))
    yaml_text = ATLAS_YAML.format(root=root, target=dump["platform"])
    (root / "atlas.yaml").write_text(yaml_text)
    (root / "mizuchi.yaml").write_text(yaml_text)
    (root / "prompts").mkdir(exist_ok=True)
    (root / "asm").mkdir(exist_ok=True)
    return out


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--binary", required=True)
    ap.add_argument("--db", type=pathlib.Path, required=True)
    ap.add_argument("--out-root", type=pathlib.Path, required=True)
    ap.add_argument("--knowledge-db", type=pathlib.Path)
    ap.add_argument("--max-functions", type=int)
    ap.add_argument("--no-asm", action="store_true")
    ap.add_argument("--no-c", action="store_true")
    a = ap.parse_args(argv)
    write(
        a.binary, out_root=a.out_root, max_functions=a.max_functions,
        with_asm=not a.no_asm, with_c=not a.no_c,
        db_path=a.db, knowledge_db=a.knowledge_db,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
