; Listing generated by Microsoft (R) Optimizing Compiler Version 13.10.3052 

	TITLE	sub_d6660.c
	.386P
include listing.inc
if @Version gt 510
.model FLAT
else
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
_BSS	SEGMENT DWORD USE32 PUBLIC 'BSS'
_BSS	ENDS
$$SYMBOLS	SEGMENT BYTE USE32 'DEBSYM'
$$SYMBOLS	ENDS
_TLS	SEGMENT DWORD USE32 PUBLIC 'TLS'
_TLS	ENDS
;	COMDAT _sub_d6660
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
FLAT	GROUP _DATA, CONST, _BSS
	ASSUME	CS: FLAT, DS: FLAT, SS: FLAT
endif

INCLUDELIB LIBC
INCLUDELIB OLDNAMES

PUBLIC	_sub_d6660
EXTRN	_PTR_sub_d6660_007465a4:DWORD
EXTRN	__free:NEAR
; Function compile flags: /Ogty
; File z:\tmp\agentdecompile-fixtures\tests\fixtures\x86\sub_d6660.c
;	COMDAT _sub_d6660
_TEXT	SEGMENT
_in_ECX$ = 8						; size = 4
_param_1$ = 8						; size = 1
_sub_d6660 PROC NEAR					; COMDAT

; 24   : {

	push	esi

; 25   :   undefined4 *in_ECX;
; 26   :   
; 27   :   *in_ECX = &PTR_sub_d6660_007465a4;

	mov	esi, DWORD PTR _in_ECX$[esp]

; 28   :   if ((void *)in_ECX[1] != (void *)0x0) {

	mov	eax, DWORD PTR [esi+4]
	test	eax, eax
	mov	DWORD PTR [esi], OFFSET FLAT:_PTR_sub_d6660_007465a4
	je	SHORT $L562

; 29   :     _free((void *)in_ECX[1]);

	push	eax
	call	__free
	add	esp, 4

; 30   :     in_ECX[1] = 0;

	mov	DWORD PTR [esi+4], 0
$L562:

; 31   :   }
; 32   :   if ((void *)in_ECX[4] != (void *)0x0) {

	mov	eax, DWORD PTR [esi+16]
	test	eax, eax
	je	SHORT $L567

; 33   :     _free((void *)in_ECX[4]);

	push	eax
	call	__free
	add	esp, 4

; 34   :     in_ECX[4] = 0;

	mov	DWORD PTR [esi+16], 0
$L567:

; 35   :   }
; 36   :   if ((param_1 & 1) != 0) {

	test	BYTE PTR _param_1$[esp], 1
	je	SHORT $L569

; 37   :     _free(in_ECX);

	push	esi
	call	__free
	add	esp, 4
$L569:
	pop	esi

; 38   :   }
; 39   :   return;
; 40   : }

	ret	0
_sub_d6660 ENDP
_TEXT	ENDS
END
